### ISSUE TITLE
所以说乱七八糟的情况太多了啊(╯▔皿▔)╯

### ISSUE THREAD

**Issue by y25552** [xyh20180101/RomajiConverter#1]
拿怪力熊的Mag Mell（マグメル）试了一下
转换的时候只般中文过去也有
嗚呼  →  
啊            啊
直接把一行省略掉不转换也有
一切合切 →  （直接没掉了）
一切
还有中间的汉字不转换的情况
朽ち果ての【慘】SHOW  →   kuchi hate no【慘】SHOW
逐渐朽烂的惨状                      逐渐朽烂的惨状
  
这有解吗
希望作者大大能解决这种问题/(ㄒoㄒ)/~~
b站发了一遍到GitHub上再反映一遍

**Comment by xyh20180101** [comment]
第一第二种情况是整行全为汉字的日文歌词被识别成中文了，这个没办法，可以试试与下一行带假名的歌词合为一行再转换。
第三种情况是词典中有“惨”的词条而没有“慘”，这种也只能手动简繁转换一下。
总的来说歌词字符问题还是要手动处理，另外转换出来的罗马音也不一定对。我技术力不够确实解决不了（

**Comment by y25552** [comment]
结果至少比网易云自带的好多了，去查了一下这个【慘】好像是什么异体字确实很多网页词典都难查出来，总之谢谢作者大大了o(*￣▽￣*)ブ

**Comment by xyh20180101** [comment]
临时加了个功能解决第三种情况，可以试下[1.0.6](https://github.com/xyh20180101/RomajiConverter/releases/tag/1.0.6)
