### ISSUE TITLE
功能很强大，页面很美观，如果能在日文汉字的上面，再加注平假名作为可选项，就完美了

### ISSUE THREAD

**Issue by ahuohuo78** [xyh20180101/RomajiConverter#3]
期待博主的继续开发~

**Comment by ahuohuo78** [comment]
该项功能可以参考同站的japankana项目

**Comment by xyh20180101** [comment]
![image](https://user-images.githubusercontent.com/36029291/218783716-84b4c3df-a965-4eb2-9ec8-ed032d110458.png)
不知道你说的是不是这种效果，这个其实就是dev分支的内容，只是我觉得这个功能可能不会有人用就没发布release
你要是觉得有用的话我再弄个假名显示上去

**Comment by ahuohuo78** [comment]
你好！我指的是给日文汉字标注平假名，观感上形成罗马音，歌词原文，不含汉字的纯假名歌词，对应显示三行（和其他功能一样作为可选开关），如果能单独识别出汉字，仅标注出汉字的假名更有利于突出重点，我这里给一个整行识别和单独识别的例子
整行识别举例
![image](https://user-images.githubusercontent.com/61161332/219087985-55f4c03c-a21c-4202-a6b8-7e07245804f7.png)
单独识别举例
![image](https://user-images.githubusercontent.com/61161332/219088435-03159541-055b-492e-9b84-9f2ca8c07ed4.png)

也可以改成在原歌词汉字后括号标注，例如
映(うつ)し出（だ）す夜（よる）

这一功能主要有利于学习日文汉字和假名的对应关系，谢谢！

**Comment by ahuohuo78** [comment]
当然，你发的图片的中段部分功能，是给分立的单词标注罗马音，这个对不熟悉50音图和基础语法的初学者，以及想直接学习日文汉字发音的人，会带来很大的帮助，如果不嫌麻烦，我也建议增加该功能，谢谢！

**Comment by xyh20180101** [comment]
我先发一个版本吧，目前是全句显示平假名，还不是你说的那种只显示汉字的，后面有时间我再补一下这个设置
[https://github.com/xyh20180101/RomajiConverter/releases/tag/1.1.0](url)
